DROP VIEW IF EXISTS create_view_p123;
DROP TABLE IF EXISTS P123;
DROP TABLE IF EXISTS numbers_10;
CREATE TABLE numbers_10(n INT);
INSERT INTO numbers_10 VALUES(0);
INSERT INTO numbers_10 VALUES(1);
INSERT INTO numbers_10 VALUES(2);
INSERT INTO numbers_10 VALUES(3);
INSERT INTO numbers_10 VALUES(4);
INSERT INTO numbers_10 VALUES(5);
INSERT INTO numbers_10 VALUES(6);
INSERT INTO numbers_10 VALUES(7);
INSERT INTO numbers_10 VALUES(8);
INSERT INTO numbers_10 VALUES(9);
CREATE TABLE P123(id INT, age INT);
INSERT INTO P123 SELECT a.n*1000 + b.n*100 + c.n*10 + d.n + 1, (a.n*1000 + b.n*100 + c.n*10 + d.n + 1) % 97 FROM numbers_10 a, numbers_10 b, numbers_10 c, numbers_10 d;
UPDATE P123 SET id = NULL WHERE (id % 17) = 0;
CREATE VIEW create_view_p123 AS SELECT id, age, id + age AS data FROM P123;
SELECT COUNT(*) AS total_rows FROM create_view_p123;
SELECT COUNT(id) AS non_null_id FROM create_view_p123;
SELECT COUNT(data) AS data_non_null FROM create_view_p123;
SELECT SUM(age) AS total_age FROM create_view_p123;
SELECT COUNT(*) AS null_id_rows FROM create_view_p123 WHERE id IS NULL;
SELECT COUNT(*) AS real_id_rows FROM create_view_p123 WHERE id IS NOT NULL;
DROP VIEW IF EXISTS v_full;
CREATE VIEW v_full AS SELECT * FROM P123;
DELETE FROM v_full WHERE id IS NULL;
INSERT INTO v_full(id, age) VALUES(10001, 18);
UPDATE v_full SET age = 99 WHERE id = 10001;
DROP VIEW IF EXISTS v_partial;
CREATE VIEW v_partial(id, age) AS SELECT id, age FROM P123;
INSERT INTO v_partial(id) VALUES(10002);
UPDATE v_partial SET age = 77 WHERE id = 10002;
DROP TABLE IF EXISTS p123_extra;
CREATE TABLE p123_extra(id INT, score INT);
INSERT INTO p123_extra VALUES(NULL, 90);
INSERT INTO p123_extra VALUES(500, 88);
INSERT INTO p123_extra VALUES(NULL, 75);
DROP VIEW IF EXISTS v_join;
CREATE VIEW v_join AS SELECT p.id, p.age, e.score FROM P123 p, p123_extra e WHERE (p.id IS NOT NULL AND p.id = e.id) OR (p.id IS NULL AND e.id IS NULL);
UPDATE v_join SET age = age + 1 WHERE id = 500;
SELECT COUNT(*) AS join_rows FROM v_join;
DROP VIEW IF EXISTS v_agg;
CREATE VIEW v_agg AS SELECT COUNT(*) AS cnt, SUM(age) AS total FROM P123;
SELECT cnt, total FROM v_agg;
