-- 测试向量索引的EXPLAIN查询
-- 测试用例：验证EXPLAIN和向量距离查询能正常工作

-- 1. 创建测试表
DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST (ID INT, C1 VECTOR(3));

-- 2. 插入测试数据
INSERT INTO TEST VALUES(1, '[1,2,3]');
INSERT INTO TEST VALUES(2, '[2,3,4]');
INSERT INTO TEST VALUES(3, '[3,4,5]');
INSERT INTO TEST VALUES(4, '[4,5,6]');
INSERT INTO TEST VALUES(5, '[5,6,7]');
INSERT INTO TEST VALUES(6, '[1,1,1]');
INSERT INTO TEST VALUES(7, '[0,0,0]');
INSERT INTO TEST VALUES(8, '[10,10,10]');

-- 3. 创建向量索引
CREATE VECTOR INDEX V_I ON TEST(C1) WITH(TYPE=IVFFLAT, DISTANCE=L2_DISTANCE, LISTS=1, PROBES=1);

-- 4. 测试EXPLAIN - 应该显示VECTOR_INDEX_SCAN
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 3;

-- 5. 执行实际查询 - 应该返回最近的3个向量
SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 3;

-- 6. 测试不同的查询向量
SELECT ID, C1, L2_DISTANCE(C1, '[0,0,0]') AS DIST FROM TEST ORDER BY L2_DISTANCE(C1, '[0,0,0]') LIMIT 2;

-- 7. 测试EXPLAIN带不同的LIMIT
EXPLAIN SELECT * FROM TEST ORDER BY L2_DISTANCE(C1, '[5,5,5]') LIMIT 5;

-- 8. 执行该查询
SELECT ID, C1, L2_DISTANCE(C1, '[5,5,5]') AS DIST FROM TEST ORDER BY L2_DISTANCE(C1, '[5,5,5]') LIMIT 5;

-- 预期结果：
-- 1. EXPLAIN应该显示 "VECTOR_INDEX_SCAN(V_I ON TEST)" 而不是崩溃
-- 2. 实际查询应该返回正确排序的结果
-- 3. 距离计算应该保留两位小数
