-- 测试向量索引优化器修复
-- 预期：EXPLAIN应该显示 PROJECT -> VECTOR_INDEX_SCAN，而不是 LIMIT -> PROJECT -> ORDER_BY -> TABLE_SCAN

-- 清理环境
DROP TABLE IF EXISTS TEST;
DROP TABLE IF EXISTS TEST2;

-- 1. 创建测试表
CREATE TABLE TEST (ID INT, C1 VECTOR(3));
CREATE TABLE TEST2 (ID INT, C1 VECTOR(3));

-- 2. 创建向量索引（注意：此时表中没有数据，索引不会ready，但优化器应该仍然使用它）
CREATE VECTOR INDEX V_I ON TEST(C1) WITH(TYPE=IVFFLAT, DISTANCE=L2_DISTANCE, LISTS=1, PROBES=1);

-- 3. 测试EXPLAIN - 应该显示使用向量索引扫描
-- 预期输出：
--   Query Plan
--   OPERATOR(NAME)
--   PROJECT
--   └─VECTOR_INDEX_SCAN(V_I ON TEST)
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 3;

-- 4. 插入一些测试数据
INSERT INTO TEST VALUES (1, '[1.0, 2.0, 3.0]');
INSERT INTO TEST VALUES (2, '[2.0, 3.0, 4.0]');
INSERT INTO TEST VALUES (3, '[0.0, 0.0, 0.0]');
INSERT INTO TEST VALUES (4, '[5.0, 5.0, 5.0]');
INSERT INTO TEST VALUES (5, '[1.5, 2.5, 3.5]');

-- 5. 再次测试EXPLAIN（有数据后索引会ready）
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 3;

-- 6. 执行实际查询，验证结果正确性
SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 3;

-- 7. 测试没有索引的情况（应该使用TABLE_SCAN）
-- 预期输出：
--   Query Plan
--   OPERATOR(NAME)
--   LIMIT
--   └─PROJECT
--     └─ORDER_BY
--       └─TABLE_SCAN(TEST2)
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST2 ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 3;

-- 8. 测试没有LIMIT的情况（不应该使用向量索引优化）
-- 预期输出：应该使用TABLE_SCAN + ORDER_BY
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]');

-- 9. 测试不同LIMIT值
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 1;
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 5;
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 10;

-- 清理
DROP TABLE TEST;
DROP TABLE TEST2;
