-- 测试向量索引重写的调试用例
-- 请在运行前确保开启TRACE日志级别

-- 初始化测试环境
DROP TABLE IF EXISTS TEST;
DROP TABLE IF EXISTS TEST2;

-- 创建测试表
CREATE TABLE TEST (ID INT, C1 VECTOR(3));
CREATE TABLE TEST2 (ID INT, C1 VECTOR(3));

-- 创建向量索引
CREATE VECTOR INDEX V_I ON TEST(C1) WITH(TYPE=IVFFLAT, DISTANCE=L2_DISTANCE, LISTS=1, PROBES=1);

-- 插入测试数据
INSERT INTO TEST VALUES (1, '[1.0, 2.0, 3.0]');
INSERT INTO TEST VALUES (2, '[2.0, 3.0, 4.0]');
INSERT INTO TEST VALUES (3, '[3.0, 4.0, 5.0]');
INSERT INTO TEST VALUES (4, '[4.0, 5.0, 6.0]');
INSERT INTO TEST VALUES (5, '[5.0, 6.0, 7.0]');

-- 关键测试：带EXPLAIN的向量查询（这是失败的场景）
EXPLAIN SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 3;

-- 对比测试：不带EXPLAIN的相同查询
SELECT C1, L2_DISTANCE(C1, '[1,2,3]') FROM TEST ORDER BY L2_DISTANCE(C1, '[1,2,3]') LIMIT 3;
